apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-service
  annotations:
    sonarqube.org/project-key: default/backdora-test
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
